classifier_path: "/facial_recog/output/classifier3.pkl"
embeddings_path: "/facial_recog/output/embeddings2.pkl"
preprocessing_path: "/facial_recog/output/beginner/"
images_dir: "/facial_recog/temp/sujeto"
lista_imagenes: "imShow/"
classifier_path: /facial_recog/temp/classifier.pkl
embeddings_path: /facial_recog/temp/embeddings.pkl
images_dir: /facial_recog/temp/sujeto
lista_imagenes: imShow/
preprocessing_path: /facial_recog/output/beginner/
classifier_path: /facial_recog/temp/classifier.pkl
embeddings_path: /facial_recog/temp/embeddings.pkl
images_dir: /facial_recog/temp/sujeto
lista_imagenes: imShow/
preprocessing_path: /facial_recog/output/beginner/
classifier_path: /facial_recog/temp/classifier.pkl
embeddings_path: /facial_recog/temp/embeddings.pkl
images_dir: /facial_recog/temp/sujeto
lista_imagenes: imShow/
preprocessing_path: /facial_recog/output/beginner/
