classifier_path: /facial_recog/output/classifier.pkl
embeddings_path: /facial_recog/output/embeddings.npy
images_dir: ../temp/sujeto
labels_path: /facial_recog/output/labels.npy
lista_imagenes: imShow/
preprocessing_path: /facial_recog/output/beginner/
